version: "2"

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/zulfikorramatov/arche

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - unconvert
    - unparam
    - errname
    - nilerr

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment

  exclusions:
    generated: lax
    paths:
      - generated/api
    rules:
      - path: pkg/redis/redis.go
        linters:
          - errname
        text: "Nil"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 3m
