openapi: 3.0.3
info:
  title: arche
  version: 1.0.0
  license:
    name: private
    url: https://tbcbank.uz
security:
  - BasicAuth: [ ]
paths:
  /users:
    get:
      operationId: ListUsers
      summary: List all users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/UserList'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: './definitions.yaml#/components/schemas/Error'
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
